package Commands;

 enum MovPrefixTo
{
  MOV_PREFIX_TO_CELL_VALUE_CELL,  MOV_PREFIX_TO_ADDRESS_VALUE_CELL,  MOV_PREFIX_TO_CELL_VALUE_CELL_ADDRESS,  MOV_PREFIX_TO_ADDRESS_VALUE_CELL_ADDRESS,  MOV_PREFIX_TO_ADDRESS_IN_CELL_VALUE_CELL,  MOV_PREFIX_TO_CELL_VALUE_ON_ADDRESS_IN_CELL,  MOV_PREFIX_TO_ADDRESS_IN_CELL_VALUE_ON_ADDRESS_IN_CELL,  MOV_PREFIX_TO_ADDRESS_VALUE_ON_ADDRES_IN_CELL,  MOV_PREFIX_TO_ADDRES_IN_CELL_VALUE_CELL_ADDRES;
  
  private MovPrefixTo() {}
}


/* Location:              /home/artem/Downloads/VM@.jar!/Commands/MovPrefixTo.class
 * Java compiler version: 7 (51.0)
 * JD-Core Version:       0.7.1
 */